# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Events
    identifier: events
    weight: 10
  - name: ACM REP 2023
    parent: events
    url: https://acm-rep.github.io/2023
    weight: 10
  - name: History
    parent: events
    url: history
    weight: 20
  - name: Blog
    url: "#blog"
    weight: 15
  - name: Steering
    url: "#steering"
    weight: 20
  - name: Diversity and Inclusion
    url: diversity
    weight: 30
  - name: Resources
    identifier: resources
    weight: 40
  - name: ACM REP Directory of Speakers
    parent: resources
    url: directory
    weight: 10
  - name: Conferences with Reproducibility
    parent: resources
    url: conferences
    weight: 20
  #- name: Nominations
  #  parent: resources
  #  url: nominations
  #  weight: 30
  - name: ACM EIGREP
    url: https://reproducibility.acm.org/
    weight: 60
